# Generated by Django 4.2 on 2023-04-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("helloword", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("example_sentence", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo_path", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="UserStudyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_name", models.CharField(max_length=64)),
                ("word_count", models.IntegerField(null=True)),
                ("last_study_date", models.DateField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.userinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=32)),
                ("phonetic_symbol", models.CharField(max_length=32)),
                ("definition_cn", models.CharField(max_length=64)),
                ("definition_en", models.CharField(max_length=255, null=True)),
                ("pronunciation_path", models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_name", models.CharField(max_length=64)),
                ("list_author_name", models.CharField(max_length=64, null=True)),
                ("description", models.CharField(max_length=255, null=True)),
                ("word_count", models.IntegerField(null=True)),
                ("gen_type", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WritingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.CharField(max_length=1023)),
                ("output", models.CharField(max_length=1023)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.userinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordsStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story", models.CharField(max_length=1023)),
                ("answers", models.CharField(max_length=255)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.userinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordsCloze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloze", models.CharField(max_length=1023)),
                ("answers", models.CharField(max_length=255)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.userinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(max_length=10)),
                (
                    "related_word_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_word",
                        to="helloword.word",
                    ),
                ),
                (
                    "word_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_word",
                        to="helloword.word",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.photo",
                    ),
                ),
                (
                    "word_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="helloword.word"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="helloword.word"
                    ),
                ),
                (
                    "word_list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.wordlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "example_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.example",
                    ),
                ),
                (
                    "word_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="helloword.word"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStudyWordInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mastery_level", models.IntegerField(default=0)),
                ("last_reviewed", models.DateTimeField()),
                ("forget_times", models.IntegerField(default=0)),
                ("simple", models.BooleanField(default=False)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.userinfo",
                    ),
                ),
                (
                    "word_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="helloword.word"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStudyListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_study_list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.userstudylist",
                    ),
                ),
                (
                    "word_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="helloword.word"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.CharField(max_length=1023)),
                ("output", models.CharField(max_length=1023)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.userinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("communication", models.CharField(max_length=1023)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helloword.userinfo",
                    ),
                ),
            ],
        ),
    ]
