# Generated by Django 3.2.9 on 2023-04-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0002_example_photo_userstudylist_word_wordlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudylist',
            name='last_study_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userstudywordinfo',
            name='last_reviewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
