# Generated by Django 4.2 on 2023-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloword", "0003_auto_20230414_1108"),
    ]

    operations = [
        migrations.RemoveField(model_name="chathistory", name="communication",),
        migrations.AddField(
            model_name="chathistory",
            name="message",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="post_time",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="chathistory", name="type", field=models.BooleanField(null=True),
        ),
    ]
