# Generated by Django 4.2 on 2023-04-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "helloword",
            "0004_remove_chathistory_communication_chathistory_message_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstudywordinfo",
            name="last_reviewed",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
