# Generated by Django 3.2.9 on 2023-04-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0005_alter_userstudywordinfo_last_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_info', models.FileField(upload_to='user_file/')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_study_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helloword.userstudylist'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_avatar',
            field=models.ImageField(default='user_avatar/default_avatar.jpg', null=True, upload_to='user_avatar/'),
        ),
        migrations.AddField(
            model_name='userstudylist',
            name='head',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
