# Generated by Django 3.2.9 on 2023-04-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0006_auto_20230416_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_study_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloword.userstudylist'),
        ),
    ]
