# Generated by Django 4.2 on 2023-04-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloword", "0007_alter_userinfo_last_study_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="password_hash",
            field=models.CharField(max_length=64),
        ),
    ]
