# Generated by Django 3.2.9 on 2023-04-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0008_alter_userinfo_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_study_date',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='not_unique_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='study_days_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userstudylistitem',
            name='has_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
