# Generated by Django 4.1.3 on 2023-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0011_auto_20230419_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition_cn',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='word',
            name='definition_en',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
