# Generated by Django 4.1.3 on 2023-04-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0012_alter_word_definition_cn_alter_word_definition_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
