# Generated by Django 4.1.3 on 2023-04-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0013_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='phonetic_symbol',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronunciation_path',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
