# Generated by Django 4.1.3 on 2023-04-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helloword", "0014_alter_word_phonetic_symbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="bnc",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="collins",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="exchange",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="frq",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="oxford",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="pos",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="tag",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="phonetic_symbol",
            field=models.CharField(max_length=64),
        ),
    ]
