# Generated by Django 4.1.3 on 2023-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helloword", "0015_word_bnc_word_collins_word_exchange_word_frq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="example_translation",
            field=models.CharField(default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="example",
            name="example_sentence",
            field=models.CharField(default="", max_length=2048),
        ),
    ]
