# Generated by Django 3.2.9 on 2023-04-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0015_word_bnc_word_collins_word_exchange_word_frq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstudylistitem',
            name='has_done',
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='post_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userstudylist',
            name='has_done',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='wordscloze',
            name='eordlist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordscloze',
            name='post_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='wordscloze',
            name='words',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordsstory',
            name='post_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='writinghistory',
            name='post_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
