# Generated by Django 3.2.9 on 2023-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0016_auto_20230421_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='example_translation',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='example',
            name='example_sentence',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
