# Generated by Django 3.2.9 on 2023-04-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0017_auto_20230422_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tags',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=64)),
                ('modules', models.CharField(default='', max_length=512)),
                ('content', models.CharField(max_length=1024)),
                ('post_time', models.DateTimeField(auto_now=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloword.userinfo')),
            ],
        ),
    ]
