# Generated by Django 3.2.9 on 2023-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0018_auto_20230423_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='tags',
            field=models.CharField(default='音乐 电影', max_length=2048, null=True),
        ),
    ]
