# Generated by Django 3.2.9 on 2023-04-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0019_alter_userinfo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.CharField(max_length=64, unique=True)),
                ('token', models.CharField(max_length=32)),
                ('gen_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
