# Generated by Django 3.2.9 on 2023-04-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0020_emailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoken',
            name='has_register',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
