# Generated by Django 3.2.9 on 2023-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0021_emailtoken_has_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='message',
            field=models.CharField(max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='readinghistory',
            name='output',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='writinghistory',
            name='output',
            field=models.CharField(max_length=4096),
        ),
    ]
