# Generated by Django 3.2.9 on 2023-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0025_userinfo_gpt_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, unique=True)),
                ('token', models.CharField(max_length=32)),
                ('gen_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
