# Generated by Django 3.2.9 on 2023-05-16 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0027_auto_20230516_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiclistcheck',
            name='check_status',
            field=models.CharField(default='user_submit', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='publiclistcheck',
            name='public_list_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helloword.wordlist'),
        ),
    ]
