# Generated by Django 3.2.9 on 2023-05-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0028_auto_20230516_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('has_read', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloword.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='publiclistcheck',
            name='send_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloword.usermessage'),
        ),
    ]
