# Generated by Django 3.2.9 on 2023-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0029_auto_20230522_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='invite_code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
