# Generated by Django 3.2.9 on 2023-05-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0032_userinfo_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='month_login',
            field=models.IntegerField(default=0),
        ),
    ]
