# Generated by Django 3.2.9 on 2023-05-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0033_userinfo_month_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(null=True, upload_to='user_voice/')),
                ('type', models.BooleanField(null=True)),
                ('post_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloword.userinfo')),
            ],
        ),
    ]
