# Generated by Django 3.2.9 on 2023-05-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0034_audiohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='custom',
            field=models.IntegerField(default=0),
        ),
    ]
