# Generated by Django 3.2.9 on 2023-06-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0035_userinfo_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='post_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
